project:
  type: book
  output-dir: docs

book:
  title: "Exploratory Data Analysis in R"
  author: "Manny Gimond"
  date: "today"
  reader-mode: true
  chapters:
   - index.qmd
   - part: "Intro"
     chapters:
       - intro.qmd
       - The_R_environment.qmd
   - part: "Data manipulation"
     chapters: 
       - data_objects.qmd
       - read_write_files.qmd
       - date_objects.qmd
       - strings.qmd
       - boolean.qmd
       - subset_base.qmd
       - dplyr.qmd
       - group_by.qmd
       - tidyr.qmd
       - joins.qmd
   - part: "Plots"
     chapters:
       - base_plots.qmd
       - lattice_plot.qmd
       - ggplot2.qmd
   - part: "Univariate"
     chapters:
       - univariate_plots.qmd
       - compare_batches.qmd
       - theoretical_qq.qmd
       - rf.qmd
       - sl_plot.qmd
       - re_express.qmd
       - letter_values.qmd
       - robustness.qmd
   - part: "Bivariate"
     chapters:
       - bivariate.qmd
       - resistant_lines.qmd
       - example.qmd
       - discontinuity.qmd
   - part: "Two-way tables"
     chapters:
       - two_way.qmd
   - part: "Miscellaneous"
     chapters:
       - rmarkdown.qmd
       - spatial.qmd
       - data.qmd
  sidebar:
    style: docked
    background: light
    title: " "
  page-footer: 
     left: |
       Manny Gimond, Creative Commons License
        [![](https://i.creativecommons.org/l/by-nc/4.0/80x15.png)](https://creativecommons.org/licenses/by-nc/4.0/) 
bibliography: references.bib

format:
  html:
    theme: haddock
    css: libs/style.css

website:
  google-analytics: "UA-39623718-2"


